services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 # For: Production
    # command: python manage.py runserver 0.0.0.0:8000 --traceback # For: Development
    volumes:
      - .:/code
    ports:
      - "8085:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: